services:
  api:
    build:
      context: . # Now pointing to the monorepo root
      dockerfile: ./apps/api/Dockerfile
    env_file: .env
    # environment:
    #   - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      # Ignore local node_modules in subfolders to prevent host/container conflicts
      - /app/apps/api/node_modules
      - /app/packages/types/node_modules
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile # Assuming your FE is here
    ports:
      - "5173:5173"
  db:
    image: postgres:18-alpine
    container_name: task-db
    env_file: .env
    hostname: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d

volumes:
  db_data:
